Repository IIC3745-Grupo-5/ProyectoA, pull requests merged in 2021-10, with the labels that each got.

#22 feat: added static scanning with sonar cloud on pull requests to main
  sonar-project copy.properties
Labels: enhancement

#17 Added feature to max flags and show them to the player
  lib/board.rb
  lib/game.rb
Labels: enhancement

#23 Fixed issue #20 and losing is way more complete :rice_ball
  lib/board.rb
  lib/cell.rb
  lib/constants/cell_type.rb
  lib/game.rb
Labels: bug fix

#24 Fixed issue #13 :rice_ball:
  lib/game.rb
Labels: bug fix, refactor

#33 fix: fix issue #32 where discovering cells throws an error
  lib/cell.rb
  lib/constants/dimensions.rb
  test/board_test.rb
Labels: bug fix
